// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SerieA.API.Context;

#nullable disable

namespace SeriA_Football.API.Migrations
{
    [DbContext(typeof(SerieAContext))]
    partial class SerieAContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SeriA_Football.API.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Week")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Matches", t =>
                        {
                            t.HasCheckConstraint("CK_Match_DifferentTeams", "[HomeTeamId] <> [AwayTeamId]");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AwayScore = 1,
                            AwayTeamId = 19,
                            HomeScore = 3,
                            HomeTeamId = 9,
                            MatchDate = new DateTime(2026, 8, 22, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "San Siro",
                            Status = 2,
                            Week = 1
                        },
                        new
                        {
                            Id = 2,
                            AwayScore = 0,
                            AwayTeamId = 15,
                            HomeScore = 2,
                            HomeTeamId = 10,
                            MatchDate = new DateTime(2026, 8, 23, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Allianz Stadium",
                            Status = 2,
                            Week = 1
                        },
                        new
                        {
                            Id = 3,
                            AwayScore = 1,
                            AwayTeamId = 18,
                            HomeScore = 2,
                            HomeTeamId = 14,
                            MatchDate = new DateTime(2026, 8, 22, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Stadio Diego Armando Maradona",
                            Status = 2,
                            Week = 1
                        },
                        new
                        {
                            Id = 4,
                            AwayScore = 1,
                            AwayTeamId = 2,
                            HomeScore = 1,
                            HomeTeamId = 17,
                            MatchDate = new DateTime(2026, 8, 23, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Stadio Olimpico",
                            Status = 2,
                            Week = 1
                        },
                        new
                        {
                            Id = 5,
                            AwayScore = 0,
                            AwayTeamId = 16,
                            HomeScore = 4,
                            HomeTeamId = 1,
                            MatchDate = new DateTime(2026, 8, 23, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Gewiss Stadium",
                            Status = 2,
                            Week = 1
                        },
                        new
                        {
                            Id = 6,
                            AwayScore = 0,
                            AwayTeamId = 3,
                            HomeScore = 1,
                            HomeTeamId = 6,
                            MatchDate = new DateTime(2026, 8, 23, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Stadio Artemio Franchi",
                            Status = 2,
                            Week = 1
                        },
                        new
                        {
                            Id = 7,
                            AwayScore = 2,
                            AwayTeamId = 13,
                            HomeScore = 1,
                            HomeTeamId = 5,
                            MatchDate = new DateTime(2026, 8, 22, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Stadio Giovanni Zini",
                            Status = 2,
                            Week = 1
                        },
                        new
                        {
                            Id = 8,
                            AwayScore = 0,
                            AwayTeamId = 11,
                            HomeScore = 0,
                            HomeTeamId = 8,
                            MatchDate = new DateTime(2026, 8, 24, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Stadio Marcantonio Bentegodi",
                            Status = 2,
                            Week = 1
                        },
                        new
                        {
                            Id = 9,
                            AwayScore = 2,
                            AwayTeamId = 7,
                            HomeScore = 2,
                            HomeTeamId = 12,
                            MatchDate = new DateTime(2026, 8, 24, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Stadio Via del Mare",
                            Status = 2,
                            Week = 1
                        },
                        new
                        {
                            Id = 10,
                            AwayScore = 1,
                            AwayTeamId = 4,
                            HomeScore = 0,
                            HomeTeamId = 20,
                            MatchDate = new DateTime(2026, 8, 23, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Bluenergy Stadium",
                            Status = 2,
                            Week = 1
                        },
                        new
                        {
                            Id = 11,
                            AwayScore = 0,
                            AwayTeamId = 20,
                            HomeScore = 2,
                            HomeTeamId = 13,
                            MatchDate = new DateTime(2026, 8, 29, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "San Siro",
                            Status = 2,
                            Week = 2
                        },
                        new
                        {
                            Id = 12,
                            AwayScore = 3,
                            AwayTeamId = 14,
                            HomeScore = 1,
                            HomeTeamId = 11,
                            MatchDate = new DateTime(2026, 8, 30, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Stadio Olimpico",
                            Status = 2,
                            Week = 2
                        },
                        new
                        {
                            Id = 13,
                            AwayScore = 1,
                            AwayTeamId = 1,
                            HomeScore = 1,
                            HomeTeamId = 19,
                            MatchDate = new DateTime(2026, 8, 30, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Stadio Olimpico Grande Torino",
                            Status = 2,
                            Week = 2
                        },
                        new
                        {
                            Id = 14,
                            AwayScore = 2,
                            AwayTeamId = 17,
                            HomeScore = 0,
                            HomeTeamId = 16,
                            MatchDate = new DateTime(2026, 8, 29, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Arena Garibaldi",
                            Status = 2,
                            Week = 2
                        },
                        new
                        {
                            Id = 15,
                            AwayScore = 1,
                            AwayTeamId = 10,
                            HomeScore = 1,
                            HomeTeamId = 7,
                            MatchDate = new DateTime(2026, 8, 30, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Stadio Luigi Ferraris",
                            Status = 2,
                            Week = 2
                        },
                        new
                        {
                            Id = 16,
                            AwayScore = 2,
                            AwayTeamId = 9,
                            HomeScore = 0,
                            HomeTeamId = 4,
                            MatchDate = new DateTime(2026, 8, 29, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Stadio Giuseppe Sinigaglia",
                            Status = 2,
                            Week = 2
                        },
                        new
                        {
                            Id = 17,
                            AwayScore = 1,
                            AwayTeamId = 6,
                            HomeScore = 2,
                            HomeTeamId = 2,
                            MatchDate = new DateTime(2026, 8, 31, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Stadio Renato Dall'Ara",
                            Status = 2,
                            Week = 2
                        },
                        new
                        {
                            Id = 18,
                            AwayScore = 0,
                            AwayTeamId = 8,
                            HomeScore = 2,
                            HomeTeamId = 3,
                            MatchDate = new DateTime(2026, 8, 30, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Unipol Domus",
                            Status = 2,
                            Week = 2
                        },
                        new
                        {
                            Id = 19,
                            AwayScore = 2,
                            AwayTeamId = 5,
                            HomeScore = 3,
                            HomeTeamId = 18,
                            MatchDate = new DateTime(2026, 8, 31, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Mapei Stadium",
                            Status = 2,
                            Week = 2
                        },
                        new
                        {
                            Id = 20,
                            AwayScore = 0,
                            AwayTeamId = 12,
                            HomeScore = 1,
                            HomeTeamId = 15,
                            MatchDate = new DateTime(2026, 8, 30, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Stadio Ennio Tardini",
                            Status = 2,
                            Week = 2
                        },
                        new
                        {
                            Id = 21,
                            AwayScore = 1,
                            AwayTeamId = 11,
                            HomeScore = 2,
                            HomeTeamId = 9,
                            MatchDate = new DateTime(2026, 9, 12, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "San Siro",
                            Status = 2,
                            Week = 3
                        },
                        new
                        {
                            Id = 22,
                            AwayScore = 1,
                            AwayTeamId = 13,
                            HomeScore = 1,
                            HomeTeamId = 17,
                            MatchDate = new DateTime(2026, 9, 13, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Stadio Olimpico",
                            Status = 2,
                            Week = 3
                        },
                        new
                        {
                            Id = 23,
                            AwayScore = 1,
                            AwayTeamId = 1,
                            HomeScore = 0,
                            HomeTeamId = 10,
                            MatchDate = new DateTime(2026, 9, 12, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Allianz Stadium",
                            Status = 2,
                            Week = 3
                        },
                        new
                        {
                            Id = 24,
                            AwayScore = 0,
                            AwayTeamId = 7,
                            HomeScore = 3,
                            HomeTeamId = 14,
                            MatchDate = new DateTime(2026, 9, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Stadio Diego Armando Maradona",
                            Status = 2,
                            Week = 3
                        },
                        new
                        {
                            Id = 25,
                            AwayScore = 2,
                            AwayTeamId = 19,
                            HomeScore = 2,
                            HomeTeamId = 6,
                            MatchDate = new DateTime(2026, 9, 12, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Stadio Artemio Franchi",
                            Status = 2,
                            Week = 3
                        },
                        new
                        {
                            Id = 26,
                            AwayScore = 0,
                            AwayTeamId = 3,
                            HomeScore = 1,
                            HomeTeamId = 2,
                            MatchDate = new DateTime(2026, 9, 13, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Stadio Renato Dall'Ara",
                            Status = 2,
                            Week = 3
                        },
                        new
                        {
                            Id = 27,
                            AwayTeamId = 15,
                            HomeTeamId = 20,
                            MatchDate = new DateTime(2026, 9, 14, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Bluenergy Stadium",
                            Status = 0,
                            Week = 3
                        },
                        new
                        {
                            Id = 28,
                            AwayTeamId = 18,
                            HomeTeamId = 8,
                            MatchDate = new DateTime(2026, 9, 14, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Stadio Marcantonio Bentegodi",
                            Status = 0,
                            Week = 3
                        },
                        new
                        {
                            Id = 29,
                            AwayTeamId = 16,
                            HomeTeamId = 12,
                            MatchDate = new DateTime(2026, 9, 14, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Stadio Via del Mare",
                            Status = 0,
                            Week = 3
                        },
                        new
                        {
                            Id = 30,
                            AwayTeamId = 4,
                            HomeTeamId = 5,
                            MatchDate = new DateTime(2026, 9, 14, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            Stadium = "Stadio Giovanni Zini",
                            Status = 0,
                            Week = 3
                        });
                });

            modelBuilder.Entity("SeriA_Football.API.Entities.MatchCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CardType")
                        .HasColumnType("int");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("Minute")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("TeamId");

                    b.ToTable("MatchCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardType = 1,
                            MatchId = 1,
                            Minute = 27,
                            PlayerName = "Saúl Coco",
                            TeamId = 19
                        },
                        new
                        {
                            Id = 2,
                            CardType = 1,
                            MatchId = 1,
                            Minute = 44,
                            PlayerName = "Hakan Çalhanoğlu",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 3,
                            CardType = 1,
                            MatchId = 1,
                            Minute = 69,
                            PlayerName = "Kristjan Asllani",
                            TeamId = 19
                        },
                        new
                        {
                            Id = 4,
                            CardType = 1,
                            MatchId = 12,
                            Minute = 30,
                            PlayerName = "Matteo Guendouzi",
                            TeamId = 11
                        },
                        new
                        {
                            Id = 5,
                            CardType = 1,
                            MatchId = 12,
                            Minute = 52,
                            PlayerName = "Stanislav Lobotka",
                            TeamId = 14
                        },
                        new
                        {
                            Id = 6,
                            CardType = 1,
                            MatchId = 12,
                            Minute = 74,
                            PlayerName = "Alessio Romagnoli",
                            TeamId = 11
                        },
                        new
                        {
                            Id = 7,
                            CardType = 2,
                            MatchId = 12,
                            Minute = 79,
                            PlayerName = "Alessio Romagnoli",
                            TeamId = 11
                        },
                        new
                        {
                            Id = 8,
                            CardType = 1,
                            MatchId = 19,
                            Minute = 19,
                            PlayerName = "Nemanja Matić",
                            TeamId = 18
                        },
                        new
                        {
                            Id = 9,
                            CardType = 1,
                            MatchId = 19,
                            Minute = 56,
                            PlayerName = "Warren Bondo",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 10,
                            CardType = 1,
                            MatchId = 19,
                            Minute = 90,
                            PlayerName = "Franco Vázquez",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 11,
                            CardType = 1,
                            MatchId = 22,
                            Minute = 15,
                            PlayerName = "Gianluca Mancini",
                            TeamId = 17
                        },
                        new
                        {
                            Id = 12,
                            CardType = 1,
                            MatchId = 22,
                            Minute = 50,
                            PlayerName = "Youssouf Fofana",
                            TeamId = 13
                        },
                        new
                        {
                            Id = 13,
                            CardType = 1,
                            MatchId = 22,
                            Minute = 61,
                            PlayerName = "Bryan Cristante",
                            TeamId = 17
                        },
                        new
                        {
                            Id = 14,
                            CardType = 3,
                            MatchId = 22,
                            Minute = 89,
                            PlayerName = "Fikayo Tomori",
                            TeamId = 13
                        });
                });

            modelBuilder.Entity("SeriA_Football.API.Entities.MatchGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("Minute")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("TeamId");

                    b.ToTable("MatchGoals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MatchId = 1,
                            Minute = 12,
                            PlayerName = "Lautaro Martínez",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 2,
                            MatchId = 1,
                            Minute = 34,
                            PlayerName = "Giovanni Simeone",
                            TeamId = 19
                        },
                        new
                        {
                            Id = 3,
                            MatchId = 1,
                            Minute = 58,
                            PlayerName = "Marcus Thuram",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 4,
                            MatchId = 1,
                            Minute = 81,
                            PlayerName = "Nicolò Barella",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 5,
                            MatchId = 12,
                            Minute = 21,
                            PlayerName = "Scott McTominay",
                            TeamId = 14
                        },
                        new
                        {
                            Id = 6,
                            MatchId = 12,
                            Minute = 39,
                            PlayerName = "Mattia Zaccagni",
                            TeamId = 11
                        },
                        new
                        {
                            Id = 7,
                            MatchId = 12,
                            Minute = 55,
                            PlayerName = "Rasmus Højlund",
                            TeamId = 14
                        },
                        new
                        {
                            Id = 8,
                            MatchId = 12,
                            Minute = 87,
                            PlayerName = "Matteo Politano",
                            TeamId = 14
                        },
                        new
                        {
                            Id = 9,
                            MatchId = 19,
                            Minute = 8,
                            PlayerName = "Domenico Berardi",
                            TeamId = 18
                        },
                        new
                        {
                            Id = 10,
                            MatchId = 19,
                            Minute = 25,
                            PlayerName = "Jamie Vardy",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 11,
                            MatchId = 19,
                            Minute = 47,
                            PlayerName = "Andrea Pinamonti",
                            TeamId = 18
                        },
                        new
                        {
                            Id = 12,
                            MatchId = 19,
                            Minute = 63,
                            PlayerName = "Federico Bonazzoli",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 13,
                            MatchId = 19,
                            Minute = 85,
                            PlayerName = "Armand Laurienté",
                            TeamId = 18
                        },
                        new
                        {
                            Id = 14,
                            MatchId = 22,
                            Minute = 38,
                            PlayerName = "Paulo Dybala",
                            TeamId = 17
                        },
                        new
                        {
                            Id = 15,
                            MatchId = 22,
                            Minute = 72,
                            PlayerName = "Rafael Leão",
                            TeamId = 13
                        });
                });

            modelBuilder.Entity("SeriA_Football.API.Entities.Substitution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("Minute")
                        .HasColumnType("int");

                    b.Property<string>("PlayerIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayerOut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("TeamId");

                    b.ToTable("Substitutions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MatchId = 1,
                            Minute = 60,
                            PlayerIn = "Duván Zapata",
                            PlayerOut = "Giovanni Simeone",
                            TeamId = 19
                        },
                        new
                        {
                            Id = 2,
                            MatchId = 1,
                            Minute = 66,
                            PlayerIn = "Cyril Ngonge",
                            PlayerOut = "Nikola Vlašić",
                            TeamId = 19
                        },
                        new
                        {
                            Id = 3,
                            MatchId = 1,
                            Minute = 70,
                            PlayerIn = "Ange-Yoan Bonny",
                            PlayerOut = "Marcus Thuram",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 4,
                            MatchId = 1,
                            Minute = 75,
                            PlayerIn = "Davide Frattesi",
                            PlayerOut = "Hakan Çalhanoğlu",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 5,
                            MatchId = 1,
                            Minute = 84,
                            PlayerIn = "Piotr Zieliński",
                            PlayerOut = "Nicolò Barella",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 6,
                            MatchId = 12,
                            Minute = 61,
                            PlayerIn = "Boulaye Dia",
                            PlayerOut = "Valentín Castellanos",
                            TeamId = 11
                        },
                        new
                        {
                            Id = 7,
                            MatchId = 12,
                            Minute = 66,
                            PlayerIn = "David Neres",
                            PlayerOut = "Kevin De Bruyne",
                            TeamId = 14
                        },
                        new
                        {
                            Id = 8,
                            MatchId = 12,
                            Minute = 70,
                            PlayerIn = "Pedro",
                            PlayerOut = "Gustav Isaksen",
                            TeamId = 11
                        },
                        new
                        {
                            Id = 9,
                            MatchId = 12,
                            Minute = 80,
                            PlayerIn = "Billy Gilmour",
                            PlayerOut = "Stanislav Lobotka",
                            TeamId = 14
                        },
                        new
                        {
                            Id = 10,
                            MatchId = 19,
                            Minute = 68,
                            PlayerIn = "Cristian Volpato",
                            PlayerOut = "Domenico Berardi",
                            TeamId = 18
                        },
                        new
                        {
                            Id = 11,
                            MatchId = 19,
                            Minute = 70,
                            PlayerIn = "Antonio Sanabria",
                            PlayerOut = "Jamie Vardy",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 12,
                            MatchId = 19,
                            Minute = 76,
                            PlayerIn = "Alberto Grassi",
                            PlayerOut = "Warren Bondo",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 13,
                            MatchId = 19,
                            Minute = 82,
                            PlayerIn = "Luca Lipani",
                            PlayerOut = "Nemanja Matić",
                            TeamId = 18
                        },
                        new
                        {
                            Id = 14,
                            MatchId = 22,
                            Minute = 60,
                            PlayerIn = "Christopher Nkunku",
                            PlayerOut = "Santiago Giménez",
                            TeamId = 13
                        },
                        new
                        {
                            Id = 15,
                            MatchId = 22,
                            Minute = 65,
                            PlayerIn = "Evan Ferguson",
                            PlayerOut = "Artem Dovbyk",
                            TeamId = 17
                        },
                        new
                        {
                            Id = 16,
                            MatchId = 22,
                            Minute = 70,
                            PlayerIn = "Ruben Loftus-Cheek",
                            PlayerOut = "Luka Modrić",
                            TeamId = 13
                        },
                        new
                        {
                            Id = 17,
                            MatchId = 22,
                            Minute = 75,
                            PlayerIn = "Stephan El Shaarawy",
                            PlayerOut = "Paulo Dybala",
                            TeamId = 17
                        });
                });

            modelBuilder.Entity("SeriA_Football.API.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Bergamo",
                            LogoUrl = "/images/logos/atalanta.png",
                            Name = "Atalanta",
                            Stadium = "Gewiss Stadium"
                        },
                        new
                        {
                            Id = 2,
                            City = "Bologna",
                            LogoUrl = "/images/logos/bologna.png",
                            Name = "Bologna",
                            Stadium = "Stadio Renato Dall'Ara"
                        },
                        new
                        {
                            Id = 3,
                            City = "Cagliari",
                            LogoUrl = "/images/logos/cagliari.png",
                            Name = "Cagliari",
                            Stadium = "Unipol Domus"
                        },
                        new
                        {
                            Id = 4,
                            City = "Como",
                            LogoUrl = "/images/logos/como.png",
                            Name = "Como",
                            Stadium = "Stadio Giuseppe Sinigaglia"
                        },
                        new
                        {
                            Id = 5,
                            City = "Cremona",
                            LogoUrl = "/images/logos/cremonese.png",
                            Name = "Cremonese",
                            Stadium = "Stadio Giovanni Zini"
                        },
                        new
                        {
                            Id = 6,
                            City = "Floransa",
                            LogoUrl = "/images/logos/fiorentina.png",
                            Name = "Fiorentina",
                            Stadium = "Stadio Artemio Franchi"
                        },
                        new
                        {
                            Id = 7,
                            City = "Cenova",
                            LogoUrl = "/images/logos/genoa.png",
                            Name = "Genoa",
                            Stadium = "Stadio Luigi Ferraris"
                        },
                        new
                        {
                            Id = 8,
                            City = "Verona",
                            LogoUrl = "/images/logos/verona.png",
                            Name = "Hellas Verona",
                            Stadium = "Stadio Marcantonio Bentegodi"
                        },
                        new
                        {
                            Id = 9,
                            City = "Milano",
                            LogoUrl = "/images/logos/inter.png",
                            Name = "Inter",
                            Stadium = "San Siro"
                        },
                        new
                        {
                            Id = 10,
                            City = "Torino",
                            LogoUrl = "/images/logos/juventus.png",
                            Name = "Juventus",
                            Stadium = "Allianz Stadium"
                        },
                        new
                        {
                            Id = 11,
                            City = "Roma",
                            LogoUrl = "/images/logos/lazio.png",
                            Name = "Lazio",
                            Stadium = "Stadio Olimpico"
                        },
                        new
                        {
                            Id = 12,
                            City = "Lecce",
                            LogoUrl = "/images/logos/lecce.png",
                            Name = "Lecce",
                            Stadium = "Stadio Via del Mare"
                        },
                        new
                        {
                            Id = 13,
                            City = "Milano",
                            LogoUrl = "/images/logos/milan.png",
                            Name = "Milan",
                            Stadium = "San Siro"
                        },
                        new
                        {
                            Id = 14,
                            City = "Napoli",
                            LogoUrl = "/images/logos/napoli.png",
                            Name = "Napoli",
                            Stadium = "Stadio Diego Armando Maradona"
                        },
                        new
                        {
                            Id = 15,
                            City = "Parma",
                            LogoUrl = "/images/logos/parma.png",
                            Name = "Parma",
                            Stadium = "Stadio Ennio Tardini"
                        },
                        new
                        {
                            Id = 16,
                            City = "Pisa",
                            LogoUrl = "/images/logos/pisa.png",
                            Name = "Pisa",
                            Stadium = "Arena Garibaldi"
                        },
                        new
                        {
                            Id = 17,
                            City = "Roma",
                            LogoUrl = "/images/logos/roma.png",
                            Name = "Roma",
                            Stadium = "Stadio Olimpico"
                        },
                        new
                        {
                            Id = 18,
                            City = "Sassuolo",
                            LogoUrl = "/images/logos/sassuolo.png",
                            Name = "Sassuolo",
                            Stadium = "Mapei Stadium"
                        },
                        new
                        {
                            Id = 19,
                            City = "Torino",
                            LogoUrl = "/images/logos/torino.png",
                            Name = "Torino",
                            Stadium = "Stadio Olimpico Grande Torino"
                        },
                        new
                        {
                            Id = 20,
                            City = "Udine",
                            LogoUrl = "/images/logos/udinese.png",
                            Name = "Udinese",
                            Stadium = "Bluenergy Stadium"
                        });
                });

            modelBuilder.Entity("SeriA_Football.API.Entities.Match", b =>
                {
                    b.HasOne("SeriA_Football.API.Entities.Team", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeriA_Football.API.Entities.Team", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("SeriA_Football.API.Entities.MatchCard", b =>
                {
                    b.HasOne("SeriA_Football.API.Entities.Match", "Match")
                        .WithMany("Cards")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeriA_Football.API.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SeriA_Football.API.Entities.MatchGoal", b =>
                {
                    b.HasOne("SeriA_Football.API.Entities.Match", "Match")
                        .WithMany("Goals")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeriA_Football.API.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SeriA_Football.API.Entities.Substitution", b =>
                {
                    b.HasOne("SeriA_Football.API.Entities.Match", "Match")
                        .WithMany("Substitutions")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeriA_Football.API.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SeriA_Football.API.Entities.Match", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Goals");

                    b.Navigation("Substitutions");
                });

            modelBuilder.Entity("SeriA_Football.API.Entities.Team", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("HomeMatches");
                });
#pragma warning restore 612, 618
        }
    }
}
